### ISSUE TITLE
Receiving connection refused error

### ISSUE THREAD

**Issue by ribru17** [disrupted/blackd-client#49]
Hello! I am trying to use this plugin with `null-ls` but whenever I run the `blackd-client` command I receive an error saying:
```
Error formatting with blackd-client: Connection refused (os error 111)
```
My config is here:
```lua
      local null_ls = require('null-ls')

      local h = require 'null-ls.helpers'
      local blackd = {
        name = 'blackd',
        method = null_ls.methods.FORMATTING,
        filetypes = { 'python' },
        generator = h.formatter_factory {
          command = 'blackd-client',
          to_stdin = true,
        },
      }

      null_ls.setup {
        sources = {
          null_ls.builtins.formatting.deno_fmt.with {
            extra_args = { '--single-quote' },
          },
          null_ls.builtins.formatting.clang_format.with {
            extra_args = { '--style', '{IndentWidth: 4}' },
          },
          blackd,
        },
      }
```
**NOTE**: This output is when I manually call the `blackd-client` command, I also tried formatting on save and this just does nothing with no error output. Thanks for your help!

**Comment by iamriel** [comment]
@ribru17 I encountered this error when blackd was not running.  Can you make sure that it's running on your end?

**Comment by disrupted** [comment]
I believe @iamriel is correct. If blackd-client is unable to connect to the blackd server, it's definitely not related to your null-ls config. Please confirm that the blackd service is running in the background. Until then I am going to close this issue.
